version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
          aws_access_key_id: $AWS_ACCESS_KEY
          aws_secret_access_key: $AWS_SECRET_KEY
      - run: aws s3 ls
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws