name: Start Backend Instance
run-name: Starting the instance
on:
    workflow_dispatch:
    push: 
      paths:
        - 'bash-scripts/instance-operation.sh'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start the Instance
        run: |
          bash bash-scripts/instance-operation.sh ${{env.AWS_INSTANCE_ID}} start ${{ secrets.SLACK_WEBHOOK_URL }}