name: Stop Backend Instance
run-name: Stopping the instance
on:
    workflow_dispatch:
    push: 
        paths:
        - 'bash-scripts/instance-operation.sh'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3