name: Stop Backend Instance
run-name: Stopping the instance
on:
    workflow_dispatch:
    repository_dispatch: 
        types:
            - stop-backend
    push: 
        paths:
        - 'bash-scripts/instance-operation.sh'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start the Instance
        run: |
          bash bash-scripts/instance-operation.sh ${{ vars.AWS_INSTANCE_ID }} stop ${{ secrets.SLACK_WEBHOOK_URL }}